### PR TITLE
Adding namespace to VaultOptions

### PR DESCRIPTION
**Pull request by mc-acc**

### CODE REVIEW

**Comment by MrZoidberg** [comment]
@mc-acc Hi. Looks awesome! Would you be able to add an additional test to check that everything works with a custom namespace?

**Comment by mc-acc** [comment]
I ran into a few problems creating an integration test.

- Namespaces appears to be a vault enterprise feature, so I cannot create an integration test using the vault docker image.
- Vaultsharp does not provide a way to create namespaces, but I was prepared to create an http request to solve this problem.

**Comment by MrZoidberg** [comment]
I've asked Hashicorp if I can use their enterprise Vault docker image for integration tests. Otherwise, I think I can make an exception and merge this.

**Comment by mc-acc** [comment]
@MrZoidberg, have you heard back from hashicorp?

I have tested this functionality against a local enterprise version of vault and it is working. I know that does not help remove the risk of future code breaking namespaces.

**Comment by MrZoidberg** [comment]
@mc-acc haven't received a word from them. Let's merge this PR and I'll make a release during this weekend

**Pull request merged**
