### PR TITLE
Expose VaultSharp's PostProcessHttpClientHandlerAction hook to allow configuring proxy settings, etc.

### PR DESCRIPTION
**Pull request by deberhar**
Hi @MrZoidberg, here's a draft PR implementing approach 1 as discussed on #47.

I did test the main project change, but I unfortunately don't have Docker for Windows available (my org doesn't license it); the added unit test is blind-coded.  Would you be able to run the test and verify it passes prior to merging, please?

### CODE REVIEW

**Comment by MrZoidberg** [comment]
@deberhar looks fine. There is a problem with your tests https://github.com/MrZoidberg/VaultSharp.Extensions.Configuration/actions/runs/7730287609/job/21283577612?pr=52 - should be easy to fix.

**Comment by deberhar** [comment]
I see... looks like `_logger` was renamed to `logger` in 340996f6b8f341c74a0df3211ea373e0bb99337d.

Let me rebase this PR to pull in that change.  One moment...

**Comment by deberhar** [comment]
Okay... if I did that right, the PR branch is now rebased onto `master`, including the one commit to add the new property + test, reparented onto 340996f6b8f341c74a0df3211ea373e0bb99337d and reflecting the `logger` field rename.

**Comment by deberhar** [comment]
Looks like the build completed and the test ran okay:
```
Passed!  - Failed:     0, Passed:    13, Skipped:     0, Total:    13, Duration: 1 m 10 s - VaultSharp.Extensions.Configuration.Test.dll (net8.0)
```
...but the build wasn't able to add a code-coverage comment on this PR.  I think it's this issue: https://github.com/marocchino/sticky-pull-request-comment/issues/930#issuecomment-1515971292.  Per the [linked article](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/):

> [...] a new trigger workflow_run was introduced to enable scenarios that require building the untrusted code and also need write permissions to update the PR with e.g. code coverage results or other test results. To do this in a secure manner, the untrusted code must be handled via the pull_request trigger so that it is isolated in an unprivileged environment. The workflow processing the PR should then store any results like code coverage or failed/passed tests in artifacts and exit. The following workflow then starts on workflow_run where it is granted write permission to the target repository and access to repository secrets, so that it can download the artifacts and make any necessary modifications to the repository or interact with third party services that require repository secrets (e.g. API tokens).

Do you want me to apply that Cancel() -> CancelAsync() suggestion before you merge?

**Comment by MrZoidberg** [comment]
that's fine since it's a test

**Comment by MrZoidberg** [comment]
Good to merge. thanks for your contribution. I'll try to release a fix today.

**Comment by deberhar** [comment]
Thank you, much appreciated!

**Pull request merged**
